//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TATdyetyf.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TATdyetyf.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Web-страница (документ HTML) представляет собой:Текстовый файл с расширением txt или doc|Текстовый файл с расширением htm или html|Двоичный файл с расширением com или exe|Графический файл с расширением gif или jpg
        ///Гипертекст - это:Текст очень большого размера|Текст, в котором используется шрифт большого размера|Структурированный текст, где возможны переходы по выделенным меткам|Текст, в который вставлены объекты с большим объемом информации
        ///Чему равно по умолчанию значение параметра SIZE тега &lt;FONT&gt;?:6|3| [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string вопросы {
            get {
                return ResourceManager.GetString("вопросы", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Текстовый файл с расширением htm или html
        ///Структурированный текст, где возможны переходы по выделенным меткам
        ///3
        ///&lt;h1&gt;&lt;/h1&gt;
        ///src
        ///print_r($arr)
        ///Internet Explorer или Opera (Google Chrome)
        ///Специальная команда, записанная в угловых скобках
        ///на любую web - страницу любого сервера Интернет
        ///Одним из средств при создании Web-страниц
        ///Web-сайтом
        ///&lt;title&gt;&lt;/title&gt;.
        /// </summary>
        internal static string Ответы {
            get {
                return ResourceManager.GetString("Ответы", resourceCulture);
            }
        }
    }
}
